### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by makasim** [webburza/payum-setefi#1]
1. https://github.com/webburza/payum-setefi/blob/master/src/Action/AuthorizeAction.php#L60 - so a user gets a blank page with OK? is it?

The rest looks great. Good job!

**Comment by dkarlovi** [comment]
Hi @makasim,

The response is to the server-to-server request which their backend does in order to confirm the transaction (so, the server get's an "OK", not the user).

The docs say we CAN send a payload here containing a different redirect URL (success instead of capture, for instance), but it doesn't say HOW the payload should look, how it's supposed to be serialized etc. We need to talk to the provider directly to clear this up.

We'll do another pass at this, add tests and a README, how to set it up stand-alone and with Sylius, will also clear this up until then.

Thank you very much for the review.

**Comment by makasim** [comment]
well, than I believe the action's name is misleading. Shouldn't it be NotifyAction?

**Comment by dkarlovi** [comment]
That's the reason why this review is great. :+1: I had some trouble figuring out which action represents which activity from Payum docs, it wasn't really clear to me, authorize seemed most appropriate.

When reviewing the lib, we'll rename the action, yes.
